behaviors:
  FetchBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.01
        demo_path: Demos/FetchBallDemo.demo
    behavioral_cloning:
      strength: 0.25
      demo_path: Demos/FetchBallDemo.demo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000